### Emoji prediction


In [2]:
#step 1 : Get the emoji package
!pip install emoji

  Created wheel for emoji: filename=emoji-0.6.0-py3-none-any.whl size=49720 sha256=9353808f5f503cdb3532ad60f02a06b80643e97dacf69ce6595bb756995603a5
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\4e\bf\6b\2e22b3708d14bf6384f862db539b044d6931bd6b14ad3c9adc
Successfully built emoji


You should consider upgrading via the 'c:\users\admin\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import emoji

In [4]:
emoji.EMOJI_UNICODE

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰',
 ':A_button_(blood_type)_selector:': '🅰️',
 ':Afghanistan:': '🇦🇫',
 ':Aland_Islands:': '🇦🇽',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱',
 ':B_button_(blood_type)_selector:': '🅱️',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧

In [6]:
emoji_dictionary = {"0": "\u2764\uFE0F",    # :heart: prints a black instead of red heart depending on the font
                    "1": ":baseball:",
                    "2": ":beaming_face_with_smiling_eyes:",
                    "3": ":downcast_face_with_sweat:",
                    "4": ":fork_and_knife:",
                    #"5" : ":hundred_points:",
                    #"6":":fire:",
                    #"7":":face_blowing_a_kiss:",
                    #"8":":chestnut:",
                    #"9" :":flexed_biceps:"
                   }

In [7]:
for e in emoji_dictionary.values():
    print(emoji.emojize(e))

❤️
⚾
😁
😓
🍴
💯
🔥
😘
🌰
💪


### Step-2 Processing custom dataset

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [14]:
train = pd.read_csv("Desktop/train_emoji.csv",header=None)

In [15]:
train.head()

0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [16]:
test =pd.read_csv("Desktop/test_emoji.csv",header=None)

In [96]:
#lets print sent with emojis
data = train.values
print(data.shape)

(132, 4)


In [97]:
x_train = train[0]
y_train = train[1]

In [98]:
from keras.utils import to_categorical

In [101]:
y_train = to_categorical(y_train,num_classes=5)
y_test = to_categorical(y_test,num_classes=5)

In [20]:
test.head()

0  1
0             I want to eat\t  4
1         he did not answer\t  3
2            he got a raise\t  2
3      she got me a present\t  0
4  ha ha ha it was so funny\t  2

In [99]:
x_test = test[0]
y_test = test[1]

In [100]:
for i in range(5):
    print(x_train[i],emoji.emojize(emoji_dictionary[str(y_train[i])]))

['never', 'talk', 'to', 'me', 'again'] 😓
['I', 'am', 'proud', 'of', 'your', 'achievements'] 😁
['It', 'is', 'the', 'worst', 'day', 'in', 'my', 'life'] 😓
['Miss', 'you', 'so', 'much'] ❤️
['food', 'is', 'life'] 🍴


### Step 3 Converting sentences into embeddings

In [36]:
f = open("Desktop/glove.6B.50d.txt",encoding='utf-8')

In [37]:
embeddings = {}
cnt = 0
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:],dtype='float')
    #print(word,coefs)
    #cnt +=1
    #if cnt ==5:
        #break
    embeddings[word] = coefs    
f.close()

In [39]:
embeddings['eat']

array([ 6.4295e-01, -4.2946e-01, -5.4277e-01, -1.0307e+00,  1.2056e+00,
       -2.7174e-01, -6.3561e-01, -1.5065e-02,  3.7856e-01,  4.6474e-02,
       -1.3102e-01,  6.0500e-01,  1.6391e+00,  2.3940e-01,  1.2128e+00,
        8.3178e-01,  7.3893e-01,  1.5200e-01, -1.4175e-01, -8.8384e-01,
        2.0829e-02, -3.2545e-01,  1.8035e+00,  1.0045e+00,  5.8484e-01,
       -6.2031e-01, -4.3296e-01,  2.3562e-01,  1.3027e+00, -8.1264e-01,
        2.3158e+00,  1.1030e+00, -6.0608e-01,  1.0101e+00, -2.2426e-01,
        1.8908e-02, -1.0931e-01,  3.8350e-01,  7.7362e-01, -8.1927e-02,
       -3.4040e-01, -1.5143e-03, -5.6640e-02,  8.7359e-01,  1.4805e+00,
        6.9421e-01, -3.0966e-01, -9.0826e-01,  3.7277e-03,  8.4550e-01])

### Step4 : converting sent into vectors(embedding output)

In [81]:
def embedding_output(X):
    max_len = 10
    emb_dim = 50
    embedding_out = np.zeros((X.shape[0],max_len,emb_dim))
    for ix in range(X.shape[0]):
        #X[ix] = X[ix].split()
        for ij in range(len(X[ix])):
            #goto every word in the current (ix) sentence
            try:
                embedding_out[ix][ij] = embeddings[X[ix][ij].lower()]
            except:
                embedding_out[ix][ij] = np.zeros((50,))
    return embedding_out
    

In [77]:
embedding_train = embedding_output(x_train)
#embedding_test = embedding_output(x_test)

In [78]:
print(x_train[0])

['never', 'talk', 'to', 'me', 'again']


In [80]:
embedding_train.shape

(132, 10, 50)

In [82]:
embedding_test = embedding_output(x_test)

In [83]:
embedding_test.shape

(56, 10, 50)

### Step - 5 Def the Rnn/LSTM model


In [84]:
from keras.models import Sequential

In [85]:
from keras.layers import *

In [144]:
model = Sequential()
model.add(LSTM(64,input_shape=(10,50),return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(64,return_sequences = False))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation("softmax"))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_8 (LSTM)                (None, 10, 64)            29440     
_________________________________________________________________
dropout_8 (Dropout)          (None, 10, 64)            0         
_________________________________________________________________
lstm_9 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dropout_9 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 325       
_________________________________________________________________
activation_5 (Activation)    (None, 5)                 0         
Total params: 62,789
Trainable params: 62,789
Non-trainable params: 0
__________________________________________________

In [145]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [125]:
print(y_train.shape)

(132, 5)


In [126]:
print(y_train[0])

[0. 0. 0. 1. 0.]


In [146]:
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
early = EarlyStopping(patience=10,monitor='val_accuracy')
check = ModelCheckpoint("best.h5",monitor='val_loss',verbose=True,save_best_only=True)
hist = model.fit(embedding_train,y_train,epochs=150,batch_size=64,shuffle=True,
                validation_split=0.2,callbacks=[check])

Epoch 1/150
1/2 [==============>...............] - ETA: 0s - loss: 1.6155 - accuracy: 0.2500
Epoch 00001: val_loss improved from inf to 1.61762, saving model to best.h5
2/2 [==============================] - 1s 512ms/step - loss: 1.6073 - accuracy: 0.2381 - val_loss: 1.6176 - val_accuracy: 0.1852
Epoch 2/150
1/2 [==============>...............] - ETA: 0s - loss: 1.5829 - accuracy: 0.3281
Epoch 00002: val_loss did not improve from 1.61762
2/2 [==============================] - 0s 20ms/step - loss: 1.5875 - accuracy: 0.2762 - val_loss: 1.6323 - val_accuracy: 0.1852
Epoch 3/150
1/2 [==============>...............] - ETA: 0s - loss: 1.5367 - accuracy: 0.3594
Epoch 00003: val_loss did not improve from 1.61762
2/2 [==============================] - 0s 22ms/step - loss: 1.5398 - accuracy: 0.3429 - val_loss: 1.6496 - val_accuracy: 0.2222
Epoch 4/150
1/2 [==============>...............] - ETA: 0s - loss: 1.5358 - accuracy: 0.3594
Epoch 00004: val_loss did not improve from 1.61762
2/2 [=========

1/2 [==============>...............] - ETA: 0s - loss: 0.6421 - accuracy: 0.8281
Epoch 00029: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 22ms/step - loss: 0.5700 - accuracy: 0.8190 - val_loss: 1.1603 - val_accuracy: 0.5185
Epoch 30/150
1/2 [==============>...............] - ETA: 0s - loss: 0.4119 - accuracy: 0.8906
Epoch 00030: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 22ms/step - loss: 0.4585 - accuracy: 0.8476 - val_loss: 1.1859 - val_accuracy: 0.5185
Epoch 31/150
1/2 [==============>...............] - ETA: 0s - loss: 0.4661 - accuracy: 0.8594
Epoch 00031: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/step - loss: 0.4437 - accuracy: 0.8571 - val_loss: 1.1962 - val_accuracy: 0.5556
Epoch 32/150
1/2 [==============>...............] - ETA: 0s - loss: 0.4398 - accuracy: 0.8281
Epoch 00032: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/st

1/2 [==============>...............] - ETA: 0s - loss: 0.0535 - accuracy: 1.0000
Epoch 00059: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 28ms/step - loss: 0.0557 - accuracy: 1.0000 - val_loss: 2.0821 - val_accuracy: 0.5556
Epoch 60/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0751 - accuracy: 1.0000
Epoch 00060: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 28ms/step - loss: 0.0598 - accuracy: 1.0000 - val_loss: 2.2891 - val_accuracy: 0.5556
Epoch 61/150
1/2 [==============>...............] - ETA: 0s - loss: 0.1119 - accuracy: 0.9688
Epoch 00061: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 25ms/step - loss: 0.1270 - accuracy: 0.9619 - val_loss: 2.0129 - val_accuracy: 0.5926
Epoch 62/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0704 - accuracy: 0.9844
Epoch 00062: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/st

1/2 [==============>...............] - ETA: 0s - loss: 0.0193 - accuracy: 1.0000
Epoch 00089: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 24ms/step - loss: 0.0209 - accuracy: 1.0000 - val_loss: 1.9015 - val_accuracy: 0.5556
Epoch 90/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0188 - accuracy: 1.0000
Epoch 00090: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/step - loss: 0.0169 - accuracy: 1.0000 - val_loss: 1.8689 - val_accuracy: 0.5185
Epoch 91/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0259 - accuracy: 1.0000
Epoch 00091: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 22ms/step - loss: 0.0214 - accuracy: 1.0000 - val_loss: 1.8363 - val_accuracy: 0.5556
Epoch 92/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0165 - accuracy: 1.0000
Epoch 00092: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 22ms/st

Epoch 119/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0442 - accuracy: 0.9844
Epoch 00119: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 26ms/step - loss: 0.0303 - accuracy: 0.9905 - val_loss: 2.2013 - val_accuracy: 0.5926
Epoch 120/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0045 - accuracy: 1.0000
Epoch 00120: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 2.0227 - val_accuracy: 0.5926
Epoch 121/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0191 - accuracy: 1.0000
Epoch 00121: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 20ms/step - loss: 0.0151 - accuracy: 1.0000 - val_loss: 1.8909 - val_accuracy: 0.5556
Epoch 122/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0064 - accuracy: 1.0000
Epoch 00122: val_loss did not improve from 1.07613
2/2 [===========================

Epoch 149/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0044 - accuracy: 1.0000
Epoch 00149: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 26ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 2.2726 - val_accuracy: 0.5926
Epoch 150/150
1/2 [==============>...............] - ETA: 0s - loss: 0.0107 - accuracy: 1.0000
Epoch 00150: val_loss did not improve from 1.07613
2/2 [==============================] - 0s 26ms/step - loss: 0.0084 - accuracy: 1.0000 - val_loss: 2.3080 - val_accuracy: 0.5926


In [147]:
pred = model.predict_classes(embedding_test)

In [148]:
pred

array([4, 3, 3, 2, 2, 2, 1, 2, 4, 3, 1, 2, 0, 3, 1, 3, 2, 2, 3, 2, 0, 3,
       4, 2, 3, 1, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 2, 4, 1, 2, 1, 0, 0, 1,
       2, 2, 2, 2, 3, 1, 3, 0, 3, 2, 3, 3], dtype=int64)

In [151]:
model.evaluate(embedding_test,y_test)

2/2 [==============================] - 0s 4ms/step - loss: 1.1869 - accuracy: 0.6250


[1.1869049072265625, 0.625]

In [150]:
model.load_weights("best.h5")

### Stacked Lstm

In [153]:
for i in range(30):
    print(''.join(x_test[i]))
    print(emoji.emojize(emoji_dictionary[str(np.argmax(y_test[i]))]))
    print(emoji.emojize(emoji_dictionary[str(pred[i])]))

Iwanttoeat
🍴
🍴
hedidnotanswer
😓
😓
hegotaraise
😁
😓
shegotmeapresent
❤️
😁
hahahaitwassofunny
😁
😁
heisagoodfriend
❤️
😁
Iamupset
❤️
⚾
Wehadsuchalovelydinnertonight
❤️
😁
whereisthefood
🍴
🍴
Stopmakingthisjokehahaha
😁
😓
whereistheball
⚾
⚾
workishard
😓
😁
Thisgirlismessingwithme
😓
❤️
areyouserioushaha
😁
😓
Letusgoplaybaseball
⚾
⚾
Thisstupidgraderisnotworking
😓
😓
workishorrible
😓
😁
Congratulationforhavingababy
😁
😁
stopmessingaround
😓
😓
anysuggestionsfordinner
🍴
😁
Ilovetakingbreaks
❤️
❤️
youbrightenmyday
😁
😓
Iboiledrice
🍴
🍴
sheisabully
😓
😁
Whyareyoufeelingbad
😓
😓
Iamupset
😓
⚾
Iworkedduringmybirthday
😓
😁
Mygrandmotheristheloveofmylife
❤️
❤️
enjoyyourbreak
😁
⚾
valentinedayisnear
❤️
😁


In [154]:
from sklearn.metrics import confusion_matrix

In [155]:
y_true = 
cm = confusion_matrix()